PROJECT = deaddrop
PROJECT_DESCRIPTION = A simple, buggy message queue.
PROJECT_VERSION = 0.1.0

DEPS = cowboy
dep_cowboy_commit = 2.6.3

BUILD_DEPS = reload_mk
DEP_PLUGINS = cowboy, reload_mk

include erlang.mk
