#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
/sbin/mdev -s

insmod /usr/supershm.ko
mknod /dev/supershm c 1337 1
chmod a+rw /dev/supershm

setsid cttyhack setuidgid 1000 sh

echo -ne "\n"
echo "To shutdown the VM, you need to kill your ssh connection. Thanks."

umount /proc
umount /sys

halt -d 1 -n -f
