import random
import string

def randomString(stringLength=8):
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for _ in range(stringLength))

class RandomUser:
    '''
    This class generates random users.

    Methods
    -------
    get_phone_number : int
        return the phone Number of the random user
    get_username : str
        return the user name of the user, computed with his lastname, the first 2
        letters of his firstname and a random number from 0 to 5000
    get_first_name : str
        return the firstame of the user
    get_last_name : str
        return the lastname of the user
    get_password : str
        return a random password generated by the function randomString
    '''

    def __init__(self):
        firstname_list = ['Michel', 'Gerard', 'Florent', 'Hugo', 'Jean-Pierre', 'Geraldine',
                            'Ovalie', 'Marie', 'Zola', 'Pomme', 'Panda', 'Megane', 'Henriette',
                             'Mamie', 'Claude', 'Angele', 'Marie', 'Christine', 'Joscha',
                             'Brunhilde', 'Eleonore', 'Claudia']
        lastname_list = ['Guttenberg', 'Garcia', 'Gillette', 'Servantes', 'Smith', 'Miller',
                            'Taylor', 'Anderson', 'Thomas',  'Willson', 'Thompson', 'Martinez',
                            'Dupont', 'Schmidt', 'Fischer', 'Bamberg', 'Gonzalez']

        self.firstname = random.choice(firstname_list)
        self.lastname = random.choice(lastname_list)
        self.username = f'{self.firstname}_{randomString(10)}son_von_{self.lastname}'
        self.password = randomString(25)

        list = [random.randint(0,9) for _ in range(10)]
        self.phone_number =  int("".join(map(str, list)))

    def get_phone_number(self):
        return self.phone_number

    def get_username(self):
        return self.username

    def get_last_name(self):
        return self.lastname

    def get_first_name(self):
        return self.firstname

    def get_password(self):
        return self.password
