version: '2.4'

services:
  sijang:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - ./service/users:/users
    ports:
      - 9999:1337
    restart: on-failure
    pids_limit: 256
    mem_limit: 500M

  sijang_market:
    build:
      context: ./service/market
      dockerfile: Dockerfile_market
    volumes:
      - ./service/market:/marketd
    restart: on-failure
    pids_limit: 256
    mem_limit: 500M
