version: '3.7'
services:
  chall1:
    build:
      context: chall1/
    working_dir: /home/ctf
    container_name: chall1
    ports:
      - "1111:1337"
    chall2:
        build:
            context: chall2/
        working_dir: /home/ctf
        container_name: chall2
        ports:
           - "2222:1337"
    chall3:
        build:
            context: chall3/
        working_dir: /home/ctf
        container_name: chall3
        ports:
           - "3333:1337"
