version: "2.4"

services:
  consul:
    build:
      context: ./attache
      dockerfile: Dockerfile
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./attache/config/config.json:/consul/config/config.json
      - consuldata:/consul/data
    cpu_percent: 50
    mem_limit: 512M
    stop_grace_period: 1s
    restart: always

  redis:
    image: redis
    volumes:
      - redisdata:/data
    cpu_percent: 50
    mem_limit: 512M
    stop_grace_period: 1s
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/home/api
    ports:
      - 20005:5000
    depends_on:
      - consul
      - redis
    pids_limit: 100
    cpu_percent: 50
    mem_limit: 512M
    stop_grace_period: 1s
    restart: always

volumes:
  consuldata:
  redisdata:
